version: 2 
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: alectolytic/rpmbuilder:centos-7
    working_directory: ~/app # directory where steps will run
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: "The .spec file check."
          command: |
            rpmlint *.spec
      - run:
          name: "Testing"
          command: pwd  
