version: 2
jobs:
  "el7":
      machine: true
      steps:
        - checkout
        - run:
            name: "Build all the .spec files for EL7 via Docker image."
            command: docker run -v ${PWD}:/sources -v ${PWD}:/output:Z ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}
            environment:
              DOCKER_IMAGE: alectolytic/rpmbuilder
              OS_ARCH: x86_64
              OS_TYPE: centos
              OS_DIST: epel
              OS_VERSION: 7
        - persist_to_workspace:
            root: /home/circleci
            paths:
              - project
workflows:
  version: 2
  build_deploy:
    jobs:
      - "el7"
      - deploy:
          requires:
            - "el7"
