version: 2 # use CircleCI 2.0
# https://circleci.com/docs/2.0/language-php/ adopted from Laravel example
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: alectolytic/rpmbuilder:centos-7
    working_directory: /sources # directory where steps will run
    steps: # a set of executable commands
      - run:
          name: "Preliminary steps that might go into Docker rpmbuild image."
          command: yum -y install git rpmlint
      - checkout # special step to check out source code to working directory
      - run:
          name: "Run rpmlint on spec files as a test."
          command: rpmlint *.spec
      - run:
          name: "Run the build itself."
          command: build
      - run:
          name: "Test for existence of built RPMs."
          command: stat /output/*.rpm
      - run:
          name: "Run rpmlint on generated RPMS."
          command: rpmlint /output/*.rpm
      - persist_to_workspace:
          root: /output
          paths:
            - "*.rpm"
  deploy:
    docker:
      - image: alectolytic/rpmbuilder:centos-7
    working_directory: /output
    steps:
      - attach_workspace:
          at: /output
      - add_ssh_keys:
          fingerprints:
            - "8c:a4:dd:2c:47:4c:63:aa:90:0b:e0:d6:15:be:87:82"
      - run:
          name: Check RPMs are still there
          command: stat *.rpm
      - run:
          name: "Deploy all RPMs to GetPageSpeed repo."
          command: scp -r *.rpm $GPS_BUILD_USER@$GPS_BUILD_SERVER:~/incoming/
          context: getpagespeed-builder
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

