version: 2 # use CircleCI 2.0
# https://circleci.com/docs/2.0/language-php/ adopted from Laravel example
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: alectolytic/rpmbuilder:centos-7
    working_directory: /sources # directory where steps will run
    steps: # a set of executable commands
      - run:
          name: "Preliminary steps that might go into Docker rpmbuild image."
          command: yum -y install git rpmlint
      - checkout # special step to check out source code to working directory
      - run:
          name: "Run rpmlint on spec files as a test."
          command: rpmlint *.spec
      - run:
          name: "Run the build itself."
          command: build
      - run:
          name: "Test for existence of built RPMs."
          command: stat /output/*.rpm
      - run:
          name: "Run rpmlint on generated RPMS."
          command: rpmlint /output/*.rpm
  deploy:
    docker:
      - image: alectolytic/rpmbuilder:centos-7
    working_directory: /output
    steps:
      - checkout
      - run:
          name: Check RPMs are still there
          command: stat *.rpm
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

